server:
  port: 8082

spring:
  main:
    allow-circular-references: true  # ✅ Corrección: Usar ":" y espacio, no "="
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:5450/studentgest
    username: postgres
    password: ABCabc123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect