server:
  port: 8083

spring:
  application:
    name: homework-service
  datasource:
    url: jdbc:postgresql://localhost:5450/studentgest
    username: postgres
    password: ABCabc123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

user-service:
  base-url: http://localhost:8080/api/users
student-service:
  base-url: http://localhost:8080/api/students