server:
  port: 8080

spring:
  application:
    name: api-gateway

# Rutas de microservicios
spring.cloud.gateway:
  routes:
    - id: student-service
      uri: http://localhost:8081
      predicates:
        - Path=/api/students/**
    - id: attendance-service
      uri: http://localhost:8082
      predicates:
        - Path=/api/asistencia/**
    - id: homework-service
      uri: http://localhost:8083
      predicates:
        - Path=/api/homework/**
    - id: user-service
      uri: http://localhost:8084
      predicates:
        - Path=/api/users/**
    - id: notification-service
      uri: http://localhost:8085
      predicates:
        - Path=/api/notificaciones/**
        - Path=/api/email/**
    - id: foro-service
      uri: http://localhost:8088
      predicates:
        - Path=/api/foro/**
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE

# Configuración JWT
jwt:
  secret: mySecretKey
  expiration: 3600000
