server:
  port: 8084

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5450/studentgest
    username: postgres
    password: ABCabc123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect